name: action_dev

on:
  workflow_dispatch:

jobs:
  action_dev:
    name: action_dev
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: choshsh/action-config-env@v0.0.1
        with:
          who-to-greet: choshsh
