name: action_dev

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  action_dev:
    name: action_dev
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: choshsh/action-config-env@v0.0.5
        id: deploy_env
        with:
          branch: ${{ github.ref_name }}
          branch-prod: master

      - name: test
        run: echo ${{ steps.deploy_env.outputs.deploy_stage }}'
