on:
  issue_comment:
    types: [created]

jobs:
  workflow_call_by_comment:
    name: Macro with comment(PR)
    if: ${{ github.event.issue.pull_request }}
    runs-on: ubuntu-latest
    env:
      GITHUB_SCRIPT_PATH: ".devops"
    steps:
      - name: Fetch CI/CD script
        uses: actions/checkout@v3
        with:
          repository: choshsh/actions
          ref: master
          path: ${{ env.GITHUB_SCRIPT_PATH }}

      - name: macro
        uses: actions/github-script@v6
        with:
          script: |
            const comment_script = require('${{ env.GITHUB_SCRIPT_PATH }}/pkg/comment/get.js')
            const comment = await comment_script({github, context})

            console.log(comment)
