name: Create pull request

on:
  workflow_call:
    inputs:
      head: # From
        required: true
        type: string
      base: # To
        required: true
        type: string

jobs:
  workflow_call_pr:
    name: Create pull request
    runs-on: ubuntu-latest
    env:
      GITHUB_SCRIPT_PATH: ".devops"
    steps:
      - name: Fetch CI/CD script
        uses: actions/checkout@v3
        with:
          repository: choshsh/actions
          ref: master
          path: ${{ env.GITHUB_SCRIPT_PATH }}

      - name: Create PR
        uses: actions/github-script@v6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          script: |
            console.log(`\n${context.payload}\n`)
            const head = "${{ inputs.head }}";
            const base = "${{ inputs.base }}";
            const title = context.payload.head_commit.message;
            const body = "Created by DevOps bot.";
            const owner = context.repo.owner;
            const repo = context.repo.repo;

            await exec.exec(
              `gh pr create --head ${head} --base ${base} --title ${title} --body ${body} --label ci`
            );
            // const pr_create_script = require('${{ env.GITHUB_SCRIPT_PATH }}/pkg/pr/create.js');
            // pr_create_script({github, context});
