name: Create pull request

on:
  workflow_call:
    inputs:
      head: # From
        required: true
        type: string
      base: # To
        required: true
        type: string

jobs:
  workflow_call_pr:
    name: Create pull request
    runs-on: ubuntu-latest
    env:
      GITHUB_SCRIPT_PATH: ".devops"
    steps:
      - uses: actions/checkout@v3
      - name: Fetch CI/CD script
        uses: actions/checkout@v3
        with:
          repository: choshsh/actions
          ref: dev
          path: ${{ env.GITHUB_SCRIPT_PATH }}

      - name: Create PR
        uses: actions/github-script@v6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          script: |
            const pr_create_script = require('${{ env.GITHUB_SCRIPT_PATH }}/pkg/pr/create.js');
            const inputs = {
              head : "${{ inputs.head }}",
              base : "${{ inputs.base }}"
             
            };
            pr_create_script({github, context, exec, inputs});
