name: Comment macro

on: workflow_call

jobs:
  workflow_call_by_comment:
    name: Macro with comment(PR)
    runs-on: ubuntu-latest
    env:
      GITHUB_SCRIPT_PATH: ".devops"
    steps:
      - name: Fetch CI/CD script
        uses: actions/checkout@v3
        with:
          repository: choshsh/actions
          ref: master
          path: ${{ env.GITHUB_SCRIPT_PATH }}

      - name: Macro
        uses: actions/github-script@v6
        with:
          script: |
            const comment_script = require('${{ env.GITHUB_SCRIPT_PATH }}/pkg/comment/get.js')
            const comment = await comment_script({github, context})

            console.log(context)
            console.log(comment)
