name: Test workflow call

on:
  push:
    paths: ["test/**"]
  issue_comment:
    types: [created]

jobs:
  test:
    if: ${{ github.event_name == 'push' }}
    uses: choshsh/actions/.github/workflows/test_env.yaml@master

  comment:
    if: ${{ github.event.issue.pull_request }}
    uses: choshsh/actions/.github/workflows/pr_comment.yaml@master
