name: Test environment

on: workflow_call

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      GITHUB_SCRIPT_PATH: ".devops"
    steps:
      - name: Fetch CI/CD script
        uses: actions/checkout@v3
        with:
          repository: choshsh/actions
          ref: master
          path: ${{ env.GITHUB_SCRIPT_PATH }}

      - name: Print env & context
        uses: actions/github-script@v6
        with:
          script: |
            const script = require('${{ env.GITHUB_SCRIPT_PATH }}/test/check_context.js')
            script({github, context})
